[package]
name = "two-fa"
version = "0.1.0"
authors = ["Evans Murithi <murithievans80@gmail.com>"]
exclude = []
repository = "https://github.com/evansmurithi/2fa"
documentation = ""
homepage = "https://github.com/evansmurithi/2fa"
readme = "README.md"
license = "MIT"
description = "A terminal based 2FA application."

[dependencies]
clap = "2.32.0"
ring = "0.13.2"
data-encoding = "2.1.1"
toml = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
open = "1.2.1"

[[bin]]
bench = false
path = "src/main.rs"
name = "2fa"
